---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyParam:
    Type: String

  EmptyParam:
    Type: String
    Default: "No Value"

Resources:
  Empty:
    Type: AWS::CloudFormation::WaitConditionHandle

  AnotherEmpty:
    Condition: Broken
    Type: AWS::CloudFormation::WaitConditionHandle
