---
name: Test usage

on:  # yamllint disable-line rule:truthy
  push: ~

jobs:
  run:
    runs-on: ubuntu-latest
    name: Test the action

    strategy:
      fail-fast: false
      matrix:
        include:
          - template: bucket.yml
            fail-flag: false
          - template: demo.yml
            fail-flag: true

    steps:
      - uses: actions/checkout@v5

      - id: lint
        name: Lint ${{ matrix.template }}
        continue-on-error: ${{ matrix.fail-flag }}
        uses: ./
        with:
          template: templates/${{ matrix.template }}

      - name: Check fails ↪️
        shell: bash
        run: |
          ./pass-intended-fails.sh \
            ${{ steps.lint.outcome }} \
            ${{ matrix.fail-flag }}
